server:
  port: 8084

spring:
  application:
    name: entrega

  datasource:
    url: jdbc:postgresql://localhost:5404/entregador
    username: postgres
    password: root

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true